steps:
  # Step 1: Build the FastAPI Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'eu.gcr.io/$PROJECT_ID/titanic-inference-api:$SHORT_SHA'
      - '-t'
      - 'eu.gcr.io/$PROJECT_ID/titanic-inference-api:latest'
      - '-f'
      - 'dockerfiles/api.dockerfile'
      - '.'

  # Step 2: Push the image to EU Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'eu.gcr.io/$PROJECT_ID/titanic-inference-api:$SHORT_SHA'

  # Step 3: Deploy to Cloud Run (europe-west1)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'titanic-inference-api'
      - '--image'
      - 'eu.gcr.io/$PROJECT_ID/titanic-inference-api:$SHORT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--service-account'
      - 'cloud-run-api@$PROJECT_ID.iam.gserviceaccount.com'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'MODEL_BUCKET=mlops-project-models,MODEL_BLOB=modelweights.pkl'

images:
  - 'eu.gcr.io/$PROJECT_ID/titanic-inference-api:$SHORT_SHA'
  - 'eu.gcr.io/$PROJECT_ID/titanic-inference-api:latest'

options:
  logging: CLOUD_LOGGING_ONLY